clean: true

theme: fullwidth

output: docs
source_directory: Sources
readme: README.md

xcodebuild_arguments:
  - -scheme
  - device-input
module: DeviceInput
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/device-input

author: ser.soft GmbH
author_url: https://sersoft.de
